### PR TITLE
fix: MSW running on prod

### LINKED ISSUE #161: Fix msw running in production enviornment
### Description
When running the app in development, MSW mocking is enabled and works as expected.
However, when running in production mode, MSW is also initialized if the NEXT_PUBLIC_API_MOCKING environment variable is set to 'true', which leads to unintended mocking in production builds.

# Current Behavior
- MSW is running in production enviornment.

### Expected Behavior
- MSW mocking should only be enabled in development environments.
- Even if NEXT_PUBLIC_API_MOCKING=true is set, mocking should be disabled when NODE_ENV !== 'development'.

### PR DESCRIPTION
**Pull request by Hariom01010**
Date: 26 Jul 2025

Developer Name: @Hariom01010  

---

## Issue Ticket Number

Closes #161 
## Description

Currently, there is a conditional check bug that allows MSW to run in production. Added an extra check to run MSW only when the environment is development and the mocking variable is set to true. In all other cases, the MSW setup does not run.
### Documentation Updated?

- [ ] Yes
- [X] No

### Under Feature Flag

- [ ] Yes
- [X] No

### Database Changes

- [ ] Yes
- [X] No

### Breaking Changes

- [ ] Yes
- [X] No

### Development Tested?

- [X] Yes
- [ ] No

## Screenshots
<details>
<summary>Screenshot 1</summary>

When the app is run in production mode using pnpm start:
image

When the app is run in development mode using pnpm run dev:
image

When the app is run in development mode and api mocking variable is false:
image

</details>

## Test Coverage
<details>
<summary>Screenshot 1</summary>

</details>

### What change is being made?

Modify the condition in `enableMocking` function to ensure MSW doesn't run on production with clearer logging.

### Why are these changes being made?

The existing condition incorrectly allowed the mocking to proceed inappropriately in some environments; this update ensures that MSW only runs in development environments when mocking is explicitly enabled, with improved log messages to better understand the environment state.

> Is this description stale? Ask me to generate a new description by commenting `/korbit-generate-pr-description`

### CODE REVIEW

File: __mocks__/init.ts [hunk 1]
```diff
@@ -1,8 +1,12 @@
 import { appConfig } from '@/config/app-config'
 
 export async function enableMocking() {
-  if (appConfig.isDev && !appConfig.isMockingEnabled) {
-    console.log(`MSW mocking disabled: ${appConfig.isDev}, ${appConfig.isMockingEnabled} `)
+  if (!(appConfig.isDev && appConfig.isMockingEnabled)) {
+    if (appConfig.isDev && !appConfig.isMockingEnabled) {
```
Comment (iamitprakash) [inline __mocks__/init.ts:5]:
```
if (!appConfig.isDev || !appConfig.isMockingEnabled) {
    if (appConfig.isDev) {
        console.log(
            `[MSW] Mocking disabled → Environment: Development, Mocking Enabled: ${appConfig.isMockingEnabled}`,
        )
    }
    return
}
```

**Review by iamitprakash — APPROVED** [review]
